export LANG="en_US.UTF-8"

# gpg suite
export GPG_TTY=$(tty)

# homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/opt:$PATH"

# python3
export PATH="$PATH:/System/Volumes/Data/Users/nikita.galaiko/Library/Python/3.8/bin"

# yarn
export PATH="$PATH:$HOME/.yarn/bin"

# golang stuff
GOPATH="$HOME/go"
GOBIN="$GOPATH/bin"
PATH="$PATH:$GOBIN"

# load plugins via antigen
source <(antibody init)
antibody bundle < "$HOME/.config/zsh/plugins.txt"

# load autocomplition
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# kubectl completion
[[ -z $(command -v kubectl) ]] || source <(kubectl completion zsh)

# aws cli completion
[[ -z $(command -v aws_completer) ]] || complete -C 'aws_completer' aws

# nvim config
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# load aliases
source "$HOME/.config/zsh/aliases"

# option navigation
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word # ⌥→

# https://github.com/zsh-users/zsh-history-substring-search
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="none"
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="none"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Enable Oh My Posh prompt. Keep at the end.
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.json)"
