export LANG="en_US.UTF-8"

# rust
source "$HOME/.cargo/env"

# hledger
export LEDGER_FILE="/Users/nikita.galaiko/Documents/ledger/main.ledger"

# gpg suite
export GPG_TTY=$(tty)

# cabal
export CABAL_BIN="/Users/nikita.galaiko/.cabal/bin"
export PATH="$CABAL_BIN:$PATH"

# pnpm
export PNPM_HOME="/Users/nikita.galaiko/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

# homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/opt:$PATH"

# python3
export PATH="$PATH:/System/Volumes/Data/Users/nikita.galaiko/Library/Python/3.8/bin"

# yarn
export PATH="$PATH:$HOME/.yarn/bin"

# golang stuff
GOPATH="$HOME/go"
GOBIN="$GOPATH/bin"
PATH="$PATH:$GOBIN"

# load plugins via antigen
source "$HOME/.config/zsh/plugins.sh"

# load autocomplition
autoload bashcompinit && bashcompinit
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# Completion for kitty
[[ -z $(command -v kitty) ]] || source "$HOME/.config/zsh/plugins/_kitty"

# kubectl completion
[[ -z $(command -v kubectl) ]] || source "$HOME/.config/zsh/plugins/_kubectl"

# aws cli completion
[[ -z $(command -v aws_completer) ]] || source "$HOME/.config/zsh/plugins/_aws"

# load aliases
source "$HOME/.config/zsh/aliases"

# option navigation
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word # ⌥→

# https://github.com/zsh-users/zsh-history-substring-search
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="none"
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="none"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# zsh autosuggest highlight style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#686868"

# kitty integration
if test -n "$KITTY_INSTALLATION_DIR"; then
    export KITTY_SHELL_INTEGRATION="enabled"
    autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
    kitty-integration
    unfunction kitty-integration
fi

# Enable Oh My Posh prompt. Keep at the end.
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.json)"
