export LANG="en_US.UTF-8"

export WEZTERM_CONFIG_FILE="$HOME/.config/wezterm/wezterm.lua"

# antidote
source "$HOME/.antidote/antidote.zsh"
source "$HOME/.config/zsh/plugins.sh"

# pnpm
export PNPM_HOME="/Users/nikita.galaiko/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# go
export GOPATH="/opt/go"

# rust
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/3.3.0/bin:$PATH"

# hledger
export LEDGER_FILE="/Users/nikita.galaiko/Documents/ledger/main.ledger"

# gpg suite
export GPG_TTY=$(tty)

# cabal
export CABAL_BIN="/Users/nikita.galaiko/.cabal/bin"
export PATH="$CABAL_BIN:$PATH"

# homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/opt:$PATH"

# python3
export PATH="$PATH:/System/Volumes/Data/Users/nikita.galaiko/Library/Python/3.8/bin"

# yarn
export PATH="$PATH:$HOME/.yarn/bin"

# load autocomplition
autoload bashcompinit && bashcompinit
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# atuin search
[[ -z $(command -v atuin) ]] || source "$HOME/.config/zsh/plugins/_atuin"

# load aliases
source "$HOME/.config/zsh/aliases"

# up/down arrow history search
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="none"
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="none"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# option navigation
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word # ⌥→

# zsh autosuggest highlight style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#686868"

eval "$(starship init zsh)"
