vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
	use(require("plugins.packer"))

	use(require("plugins.autopairs"))
	use(require("plugins.cmp"))
	use(require("plugins.comment"))
	use(require("plugins.conform"))
	use(require("plugins.fugitive"))
	use(require("plugins.gitsigns"))
	use(require("plugins.line"))
	use(require("plugins.lint"))
	use(require("plugins.lsp"))
	use(require("plugins.navigator"))
	use(require("plugins.symbols-outline"))
	use(require("plugins.telescope"))
	use(require("plugins.tree"))
	use(require("plugins.treesitter"))
	use(require("plugins.trouble"))
	use(require("plugins.undotree"))
	use(require("plugins.zenbones"))
end)
