" Generated by vim-plug
" Wed Nov 29 09:01:03 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = '0236521ea582747b58869cb72f70ccfa967d2e89'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = '8ee981b4a91f536f52add291594e89fb6645e451'
silent! let g:plugs['cmp-nvim-lsp'].commit = '44b16d11215dce86f253ce0c30949813c0a90765'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['copilot.lua'].commit = '3665ed0f3ef3ad68673df7195789d134d0d1fdb0'
silent! let g:plugs['gitsigns.nvim'].commit = '175e74f87d3d2e4d20952d390af5f2a794f5ed7e'
silent! let g:plugs['lualine.nvim'].commit = '2248ef254d0a1488a72041cfb45ca9caada6d994'
silent! let g:plugs['lush.nvim'].commit = '966aad1accd47fa11fbe2539234f81f678fef2de'
silent! let g:plugs['null-ls.nvim'].commit = '0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7'
silent! let g:plugs['nvim-autopairs'].commit = '0f04d78619cce9a5af4f355968040f7d675854a1'
silent! let g:plugs['nvim-cmp'].commit = '0b751f6beef40fd47375eaf53d3057e0bfa317e4'
silent! let g:plugs['nvim-lspconfig'].commit = '39546f730bdff8eccf7cec344cfce694f19ac908'
silent! let g:plugs['nvim-tree.lua'].commit = '05f55c1fd6470b31627655c528245794e3cd4b2c'
silent! let g:plugs['nvim-treesitter'].commit = 'b04f990f92e41d0909de20a970a4a3c0fde5557e'
silent! let g:plugs['nvim-treesitter-context'].commit = 'bf4d15ee4e96ff5201f16a4ed14443670662eb90'
silent! let g:plugs['nvim-web-devicons'].commit = '5efb8bd06841f91f97c90e16de85e96d57e9c862'
silent! let g:plugs['plenary.nvim'].commit = '366b0837486f60ae0e7550c15de8ff66d057c4cd'
silent! let g:plugs['popup.nvim'].commit = 'b7404d35d5d3548a82149238289fa71f7f6de4ac'
silent! let g:plugs['symbols-outline.nvim'].commit = '512791925d57a61c545bc303356e8a8f7869763c'
silent! let g:plugs['telescope.nvim'].commit = '84c5a71d825b6687a55aed6f41e98b92fd8e5454'
silent! let g:plugs['trouble.nvim'].commit = 'f1168feada93c0154ede4d1fe9183bf69bac54ea'
silent! let g:plugs['vim-fugitive'].commit = '46eaf8918b347906789df296143117774e827616'
silent! let g:plugs['vim-kitty-navigator'].commit = 'c3d8aaaa61717b2c142ff39553fcab709fd606a7'
silent! let g:plugs['vim-ledger'].commit = '281346a221434574dd7f8767a352b2bf0b218b74'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['zenbones.nvim'].commit = '510d12c088ed45a410371c63ebd62ffb54c1615f'

PlugUpdate!

