" Generated by vim-plug
" Fri Sep 30 09:02:07 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'c66c379915d68fb52ad5ad1195cdd4265a95ef1e'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-omni'].commit = '7a457f0c4f9e0801fee777d955eb841659aa3b84'
silent! let g:plugs['cmp-path'].commit = '447c87cdd6e6d6a1d2488b1d43108bfa217f56e1'
silent! let g:plugs['cmp-vsnip'].commit = '0abfa1860f5e095a07c477da940cfcb0d273b700'
silent! let g:plugs['gitsigns.nvim'].commit = 'f98c85e7c3d65a51f45863a34feb4849c82f240f'
silent! let g:plugs['gruvbox.nvim'].commit = 'd2fdcdb1822264c256bf38a56efc1c3d4ecc337f'
silent! let g:plugs['lualine.nvim'].commit = 'a52f078026b27694d2290e34efa61a6e4a690621'
silent! let g:plugs['lush.nvim'].commit = 'fabf012e243bc58c4785ab4c44f05e94b34c431a'
silent! let g:plugs['null-ls.nvim'].commit = 'c8624325198513411cf9dcacde76f14d2260220f'
silent! let g:plugs['nvim-autopairs'].commit = '14cc2a4fc6243152ba085cc2059834113496c60a'
silent! let g:plugs['nvim-cmp'].commit = '2427d06b6508489547cd30b6e86b1c75df363411'
silent! let g:plugs['nvim-lspconfig'].commit = 'ad35a8cfa5086451e33af477a02bffa916dbe0ce'
silent! let g:plugs['nvim-tree.lua'].commit = '43fd13854423666c53439536892a5fbc4a66044c'
silent! let g:plugs['nvim-treesitter'].commit = '9bfaf62e42bdcd042df1230e9188487e62a112c0'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '75f5895cc662d61eb919da8050b7a0124400d589'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '41e8d8964e5c874d9ce5e37d00a52f37f218502e'
silent! let g:plugs['nvim-ts-context-commentstring'].commit = '4d3a68c41a53add8804f471fcc49bb398fe8de08'
silent! let g:plugs['nvim-web-devicons'].commit = '503418a130423f59e57027fd7db8bcee007d29d1'
silent! let g:plugs['playground'].commit = 'e6a0bfaf9b5e36e3a327a1ae9a44a989eae472cf'
silent! let g:plugs['plenary.nvim'].commit = '9e7c62856e47053ec7b17f82c5da0f1e678d92c8'
silent! let g:plugs['popup.nvim'].commit = 'b7404d35d5d3548a82149238289fa71f7f6de4ac'
silent! let g:plugs['symbols-outline.nvim'].commit = '6a3ed24c5631da7a5d418bced57c16b32af7747c'
silent! let g:plugs['telescope.nvim'].commit = 'd4204618dddf1628e7a19ad4a7b910864d1120a5'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-cooklang'].commit = '861b7abd74f4606398bb3c7bc8d326f500e1340c'
silent! let g:plugs['vim-fugitive'].commit = 'dd8107cabf5fe85df94d5eedcae52415e543f208'
silent! let g:plugs['vim-go'].commit = '22b2273cfe562ac1c1af976ce77f18a3b1776f3c'
silent! let g:plugs['vim-kitty-navigator'].commit = 'e48aae3c7e3136682b3f4c6cfd85867b392f7f1a'
silent! let g:plugs['vim-ledger'].commit = '519befb7004bf3a66a3ddfdc2d431b0bd360dc97'
silent! let g:plugs['vim-rhubarb'].commit = 'cad60fe382f3f501bbb28e113dfe8c0de6e77c75'
silent! let g:plugs['vim-terraform'].commit = 'f0b17ac9f1bbdf3a29dba8b17ab429b1eed5d443'
silent! let g:plugs['vim-vsnip'].commit = '8f199ef690ed26dcbb8973d9a6760d1332449ac9'
silent! let g:plugs['zenbones.nvim'].commit = '6455bdfa0ef8d8ef1dd6412608f82aa04b629d9c'

PlugUpdate!

