" Generated by vim-plug
" Wed Jun 19 16:11:01 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = 'e30b7f2008e52442154b66f7c519bfd2f1e32acb'
silent! let g:plugs['Navigator.nvim'].commit = '91d86506ac2a039504d5205d32a1d4bc7aa57072'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'd250c63aa13ead745e3a40f61fdd3470efde3923'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['copilot.lua'].commit = '86537b286f18783f8b67bccd78a4ef4345679625'
silent! let g:plugs['gitsigns.nvim'].commit = '651d5ed082605f3ed96b0f037a768ca06ecf8fc3'
silent! let g:plugs['lualine.nvim'].commit = '0a5a66803c7407767b799067986b4dc3036e1983'
silent! let g:plugs['lush.nvim'].commit = '7c0e27f50901481fe83b974493c4ea67a4296aeb'
silent! let g:plugs['none-ls.nvim'].commit = 'cc0a3c45047e3daf85d07c1571d65476cfce6480'
silent! let g:plugs['nvim-autopairs'].commit = 'c15de7e7981f1111642e7e53799e1211d4606cb9'
silent! let g:plugs['nvim-cmp'].commit = 'a110e12d0b58eefcf5b771f533fc2cf3050680ac'
silent! let g:plugs['nvim-lspconfig'].commit = '5c33bf1f708ac8cb839469e1a03d45987fec305c'
silent! let g:plugs['nvim-tree.lua'].commit = '2086e564c4d23fea714e8a6d63b881e551af2f41'
silent! let g:plugs['nvim-treesitter'].commit = '66ae8748fd4e8550c8b17cf115c9739aea1e4067'
silent! let g:plugs['nvim-treesitter-context'].commit = '5efba33af0f39942e426340da7bc15d7dec16474'
silent! let g:plugs['nvim-web-devicons'].commit = 'c0cfc1738361b5da1cd0a962dd6f774cc444f856'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['popup.nvim'].commit = 'b7404d35d5d3548a82149238289fa71f7f6de4ac'
silent! let g:plugs['symbols-outline.nvim'].commit = '564ee65dfc9024bdde73a6621820866987cbb256'
silent! let g:plugs['telescope.nvim'].commit = 'c392f1b78eaaf870ca584bd698e78076ed301b26'
silent! let g:plugs['trouble.nvim'].commit = '58a3acfc6d8d819324dab4c87068596319032e64'
silent! let g:plugs['vim-fugitive'].commit = '64d6cafb9dcbacce18c26d7daf617ebb96b273f3'
silent! let g:plugs['vim-ledger'].commit = '7b97c8765bf920e92fd950a7a5bc37cb2b13a494'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['zenbones.nvim'].commit = 'e9ba8305f65524f9355515cdd8704b2c6ba2def6'

PlugUpdate!

